<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>FireCommandModels</Title>
    <Authors>$(AssemblyName);raul;rgm</Authors>
    <Product>$(AssemblyName);raul;rgm</Product>
    <PackageIcon>firecommand.jpg</PackageIcon>
    <Version>7.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\..\..\..\Proyectos\portfolio\public\firecommand.jpg">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
